# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.9.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:latest
        environment:
          POSTGRES_PASSWORD: postgres

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Setup environment
          command: |
            mix local.hex --force
            mix local.rebar --force

      - run:
          name: Test application
          command: MIX_ENV=test mix do deps.get, ecto.create, test

      - run:
          name: Build and push Docker image
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              TAG=0.1.$CIRCLE_BUILD_NUM
              docker build -t $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$TAG .
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$TAG
            fi
