# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.9.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:latest
        environment:
          POSTGRES_PASSWORD: postgres

    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Test application
          command: |
            mix local.hex --force
            mix local.rebar --force
            MIX_ENV=test mix do deps.get, ecto.create, test

      - run:
          name: Run application using Docker compose
          command: cd docker && docker-compose up -d

      - run:
          name: ZAP baseline test of application
          # Only fail on error code 1, which indicates at least one FAIL was found;
          # error codes 2 & 3 indicate WARN or other, and should not break the run.
          command: |
            (
              docker pull owasp/zap2docker-weekly && \
              docker run -t --network docker_sdo-phenix owasp/zap2docker-weekly \
                zap-baseline.py -t http://sdo-phenix:4000/ || \
              if [ $? -ne 1 ]; then exit 0; else exit 1; fi
            )

      - run:
          name: Build and push Docker image
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker build -t $DOCKER_USER/$CIRCLE_PROJECT_REPONAME .
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
            fi
