version: "3"
services:
  sdo-phenix:
    build: ..
    ports:
      - "4000:4000"
    links:
      - postgres
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ecto://postgres:${POSTGRES_PASSWORD}@postgres/postgres
    networks:
      - sdo-phenix
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - sdo-phenix
networks:
  sdo-phenix:
    driver: bridge
